color:
  channel: "WHITE"
  conversation: "LIGHT_PURPLE"
default-channel: "Global"
format:
  announce: "{color}{message}"
  broadcast: "{color}[{bc-prefix}{color}] {message}"
  chat: "{color}[{nick}]{sender}{color}: {message}"
  conversation: "{color}[{con-address} {con-partner}{color}] {message}"
locale: "en"
log:
  chat: true
  colored: true
  conversation: true
  debug: false
  to-console: true
  to-file: true