main: de.g4memas0n.chats.Chats
name: Chats
version: 1.0.0-pre3
description: A Plugin that provides a channel based chat.
author: G4meMas0n
api-version: '1.13'

softdepend:
  - Vault
loadbefore:
  - Herochat

commands:
  # Basic plugin commands:
  channel:
    aliases: [ch]
    description: Manages the channels.
    permission: chats.channel
    usage: /channel <command> [<arguments>]
  chats:
    description: The main plugin command.
    permission: chats.use
    usage: /chats <command> [<arguments>]

  # Chatter plugin commands:
  chat:
    description: Sends a message in a channel without changing the focused channel.
    permission: chats.speak
    usage: /chat <channel> <message>
  focus:
    description: Focuses a new channel.
    permission: chats.focus
    usage: /focus <channel> [<password>]
  ignore:
    description: Ignores a player.
    permission: chats.ignore
    usage: /ignore <player>
  join:
    description: Joins a new channel.
    permission: chats.join
    usage: /join <channel> [<password>]
  leave:
    description: Leaves a channel.
    permission: chats.leave
    usage: /leave <channel>
  msg:
    aliases: [pm, tell, whisper, w]
    description: Starts a conversation with or sends a private message to a chatter.
    permission: chats.msg
    usage: /msg <player> [<message>]
  reply:
    aliases: [r]
    description: Starts a conversation with or sends a private message to the last conversation partner.
    permission: chats.msg
    usage: /reply [<message>]
  unignore:
    description: Unignores a player.
    permission: chats.ignore
    usage: /unignore <player>

permissions:
  # Basic moderate permission.
  chats.moderate:
    description: Allows to access moderating channel commands.
    default: false
    children:
      chats.ban: true
      chats.broadcast: true
      chats.kick: true
      chats.mute: true
      chats.pardon: true

  # Wildcard permissions:
  chats.create.type.*:
    description: Allows to create all channel types.
    default: false
    children:
      chats.create.type.persist: true
      chats.create.type.standard: true

  chats.delete.type.*:
    description: Allows to delete all channel types.
    default: false
    children:
      chats.delete.type.persist: true
      chats.delete.type.standard: true

  chats.list.type.*:
    description: Allows to list all channel types.
    default: false
    children:
      chats.list.type.conversation: true
      chats.list.type.standard: true
      chats.list.type.persist: true

  chats.modify.type.*:
    description: Allows to modify all modify types.
    default: false
    children:
      chats.modify.type.announce-format: true
      chats.modify.type.broadcast-format: true
      chats.modify.type.chat-format: true
      chats.modify.type.color: true
      chats.modify.type.cross-world: true
      chats.modify.type.custom-format: true
      chats.modify.type.distance: true
      chats.modify.type.moderator: true
      chats.modify.type.owner: true
      chats.modify.type.password: true
      chats.modify.type.short-name: true

  chats.view.type.*:
    description: Allows to view all info types.
    default: false
    children:
      chats.view.type.color: true
      chats.view.type.cross-world: true
      chats.view.type.distance: true
      chats.view.type.format: true
      chats.view.type.moderators: true
      chats.view.type.mutes: true
      chats.view.type.owner: true
      chats.view.type.password: true
      chats.view.type.short-name: true
      chats.view.type.type: true

  chats.view.*:
    description: Allows to view all channel informations.
    default: false
    children:
      chats.view.info: true
      chats.view.info.persist.all: true
      chats.view.info.standard.all: true
      chats.view.type.*: true
      chats.view.who: true
      chats.view.who.persist.all: true
      chats.view.who.standard.all: true

  chats.reload.type.*:
    description: Allows to reload all reload types.
    default: false
    children:
      chats.reload.type.all: true
      chats.reload.type.channels: true
      chats.reload.type.chatters: true
      chats.reload.type.config: true

  chats.save.type.*:
    description: Allows to reload all reload types.
    default: false
    children:
      chats.save.type.all: true
      chats.save.type.channels: true
      chats.save.type.chatters: true
      chats.save.type.config: true
