name: "Default"
nick: "D"
color: "WHITE"
cross-world: true
distance: -1
password: ""
format:
  announce: "{color}{message}"
  broadcast: "{color}[{bc-prefix}{color}] {message}"
  channel: "{color}[{nick}]{sender}{color}: {message}"
  use-custom: false